export const FORMULAS = [
  {
    formulaId: 'APT-FOR-001',
    conceptSlug: 'number-system',
    title: 'Sum of First n Natural Numbers',
    expression: '1+2+3+\\cdots+n = \\dfrac{n(n+1)}{2}',
    plainText: 'Sum = n(n+1)/2',
    explanation: 'Add all integers from 1 to n. Used in series sum problems.',
    derivation: 'Pair first and last: (1+n)+(2+n-1)+... each pair sums to n+1, and there are n/2 pairs.',
    tags: ['series', 'sum', 'natural-numbers'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-002',
    conceptSlug: 'number-system',
    title: 'Sum of Squares of First n Natural Numbers',
    expression: '1^2+2^2+\\cdots+n^2 = \\dfrac{n(n+1)(2n+1)}{6}',
    plainText: 'Sum of squares = n(n+1)(2n+1)/6',
    explanation: 'Used when asked for sum like 1²+2²+...+n².',
    derivation: '',
    tags: ['series', 'squares', 'sum'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-003',
    conceptSlug: 'number-system',
    title: 'Sum of Cubes of First n Natural Numbers',
    expression: '1^3+2^3+\\cdots+n^3 = \\left[\\dfrac{n(n+1)}{2}\\right]^2',
    plainText: 'Sum of cubes = [n(n+1)/2]^2',
    explanation: 'Sum of cubes equals the square of the sum of first n numbers.',
    derivation: '',
    tags: ['series', 'cubes', 'sum'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-004',
    conceptSlug: 'number-system',
    title: '(a+b)² Expansion',
    expression: '(a+b)^2 = a^2 + 2ab + b^2',
    plainText: '(a+b)^2 = a^2 + 2ab + b^2',
    explanation: 'Square of a sum. Use to quickly compute large squares like 1605²=(1600+5)².',
    derivation: 'Multiply (a+b)(a+b) term by term.',
    tags: ['algebra', 'identity', 'expansion'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-005',
    conceptSlug: 'number-system',
    title: '(a-b)² Expansion',
    expression: '(a-b)^2 = a^2 - 2ab + b^2',
    plainText: '(a-b)^2 = a^2 - 2ab + b^2',
    explanation: 'Square of a difference. Use to compute squares like 1397²=(1400-3)².',
    derivation: '',
    tags: ['algebra', 'identity', 'expansion'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-006',
    conceptSlug: 'number-system',
    title: 'Sum and Difference of Squares Identity',
    expression: '(a+b)^2 + (a-b)^2 = 2(a^2+b^2)',
    plainText: '(a+b)^2 + (a-b)^2 = 2(a^2+b^2)',
    explanation: 'Useful when sum of two squares and sum/difference are given.',
    derivation: 'Add (a+b)² and (a-b)² and simplify.',
    tags: ['algebra', 'identity'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-007',
    conceptSlug: 'number-system',
    title: 'Difference of Squares',
    expression: 'a^2 - b^2 = (a+b)(a-b)',
    plainText: 'a^2 - b^2 = (a+b)(a-b)',
    explanation: 'Key factoring formula. E.g. 796²-204²=(796+204)(796-204)=1000×592.',
    derivation: '',
    tags: ['algebra', 'factoring', 'difference-of-squares'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-008',
    conceptSlug: 'number-system',
    title: 'Sum of Cubes Factoring',
    expression: 'a^3+b^3 = (a+b)(a^2-ab+b^2)',
    plainText: 'a^3+b^3 = (a+b)(a^2-ab+b^2)',
    explanation: 'Used in problems like (789³+211³)/(789²-789×211+211²) = 789+211 = 1000.',
    derivation: '',
    tags: ['algebra', 'cubes', 'factoring'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-009',
    conceptSlug: 'number-system',
    title: 'Difference of Cubes Factoring',
    expression: 'a^3-b^3 = (a-b)(a^2+ab+b^2)',
    plainText: 'a^3-b^3 = (a-b)(a^2+ab+b^2)',
    explanation: 'Factor difference of cubes. Used in (658³-328³)/(658²+658×328+328²) = 658-328 = 330.',
    derivation: '',
    tags: ['algebra', 'cubes', 'factoring'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-010',
    conceptSlug: 'number-system',
    title: 'Division Algorithm (Euclidean)',
    expression: '\\text{Dividend} = \\text{Divisor} \\times \\text{Quotient} + \\text{Remainder}',
    plainText: 'Dividend = Divisor × Quotient + Remainder',
    explanation: 'Fundamental relation for all division problems. Remainder is always 0 ≤ R < Divisor.',
    derivation: '',
    tags: ['division', 'remainder', 'fundamental'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-011',
    conceptSlug: 'number-system',
    title: 'Trailing Zeros in n!',
    expression: '\\text{Trailing zeros in } n! = \\left\\lfloor\\frac{n}{5}\\right\\rfloor + \\left\\lfloor\\frac{n}{25}\\right\\rfloor + \\left\\lfloor\\frac{n}{125}\\right\\rfloor + \\cdots',
    plainText: 'Trailing zeros = floor(n/5) + floor(n/25) + floor(n/125) + ...',
    explanation: 'Each trailing zero needs one factor of 2 and one of 5. 5s are limiting. Count all multiples of 5, 25, 125... in n!',
    derivation: 'Trailing zeros = pairs of (2×5). Factors of 2 always exceed factors of 5, so count only factors of 5.',
    tags: ['trailing-zeros', 'factorial', 'counting'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-012',
    conceptSlug: 'number-system',
    title: 'Highest Power of Prime p in n!',
    expression: 'E_p(n!) = \\left\\lfloor\\frac{n}{p}\\right\\rfloor + \\left\\lfloor\\frac{n}{p^2}\\right\\rfloor + \\left\\lfloor\\frac{n}{p^3}\\right\\rfloor + \\cdots',
    plainText: 'Legendre\'s formula: E_p(n!) = floor(n/p) + floor(n/p^2) + ...',
    explanation: 'Finds exact power of prime p in n!. Sum until p^k > n.',
    derivation: 'Multiples of p contribute one factor, multiples of p² contribute an extra, and so on.',
    tags: ['prime', 'factorial', 'power'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-013',
    conceptSlug: 'number-system',
    title: '(xⁿ - aⁿ) Divisibility Rule',
    expression: '(x^n - a^n) \\text{ is divisible by } (x-a) \\text{ for all } n \\in \\mathbb{N}',
    plainText: '(x^n - a^n) is always divisible by (x - a)',
    explanation: 'E.g. 9⁶-1⁶ is divisible by 9-1=8. So 9⁶+7 = (9⁶-1)+8 divisible by 8.',
    derivation: 'Factor: xⁿ-aⁿ = (x-a)(x^(n-1)+x^(n-2)a+...+aⁿ⁻¹)',
    tags: ['divisibility', 'algebraic', 'remainder'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-014',
    conceptSlug: 'number-system',
    title: '(xⁿ - aⁿ) Divisible by (x+a) for Even n',
    expression: '(x^n - a^n) \\text{ divisible by } (x+a) \\text{ when } n \\text{ is even}',
    plainText: '(x^n - a^n) divisible by (x+a) for even n',
    explanation: 'E.g. 257¹⁶⁶ - 243¹⁶⁶ is divisible by 257+243=500.',
    derivation: '',
    tags: ['divisibility', 'algebraic'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-015',
    conceptSlug: 'number-system',
    title: '(xⁿ + aⁿ) Divisible by (x+a) for Odd n',
    expression: '(x^n + a^n) \\text{ divisible by } (x+a) \\text{ when } n \\text{ is odd}',
    plainText: '(x^n + a^n) divisible by (x+a) for odd n',
    explanation: 'E.g. 127¹²⁷+97¹²⁷ is divisible by 127+97=224. Also (397)³⁵⁸⁹+1 divisible by 398.',
    derivation: '',
    tags: ['divisibility', 'algebraic', 'remainder'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-016',
    conceptSlug: 'number-system',
    title: 'Sum of First n Even Numbers',
    expression: '2+4+6+\\cdots+2n = n(n+1)',
    plainText: 'Sum of first n even numbers = n(n+1)',
    explanation: 'For series 2+4+...+2n. If last term L is given, n = L/2.',
    derivation: '= 2(1+2+...+n) = 2·n(n+1)/2 = n(n+1)',
    tags: ['series', 'even', 'sum'],
    source: 'ppt',
  },
  {
    formulaId: 'APT-FOR-017',
    conceptSlug: 'number-system',
    title: 'Sum of First n Odd Numbers',
    expression: '1+3+5+\\cdots+(2n-1) = n^2',
    plainText: 'Sum of first n odd numbers = n^2',
    explanation: 'For series 1+3+5+...+L (odd), n=(L+1)/2, sum=n².',
    derivation: '',
    tags: ['series', 'odd', 'sum'],
    source: 'ppt',
  },
  {
    formulaId: 'APT-FOR-018',
    conceptSlug: 'number-system',
    title: 'Unit Digit of Powers (Cyclicity)',
    expression: '\\text{Unit digit of } a^n = \\text{Unit digit of } (\\text{unit digit of } a)^{n \\bmod 4}',
    plainText: 'Unit digit of a^n depends on unit digit of a and (n mod 4). Cycle length is 4 for most digits.',
    explanation: 'Digits 0,1,5,6 always give same unit digit. 4 and 9 have cycle 2. Others (2,3,7,8) have cycle 4.',
    derivation: 'Powers of any digit repeat in a cycle of at most 4.',
    tags: ['unit-digit', 'cyclicity', 'powers'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-019',
    conceptSlug: 'number-system',
    title: 'Divisibility by 11',
    expression: '\\text{Divisible by 11 iff } (\\text{Sum of odd-position digits}) - (\\text{Sum of even-position digits}) = 0 \\text{ or multiple of 11}',
    plainText: '(Sum of digits at odd places) - (Sum of digits at even places) = 0 or multiple of 11',
    explanation: 'Count positions from right. E.g. 29435417: odd positions sum=23, even positions sum=12, diff=11.',
    derivation: '10 ≡ -1 (mod 11), so each digit alternates sign.',
    tags: ['divisibility', '11', 'test'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-020',
    conceptSlug: 'number-system',
    title: 'Arithmetic Progression: nth Term',
    expression: 'a_n = a + (n-1)d',
    plainText: 'nth term = first term + (n-1) × common difference',
    explanation: 'a = first term, d = common difference, n = term number.',
    derivation: '',
    tags: ['AP', 'series', 'arithmetic-progression'],
    source: 'ppt',
  },
  {
    formulaId: 'APT-FOR-021',
    conceptSlug: 'number-system',
    title: 'Arithmetic Progression: Sum of n Terms',
    expression: 'S_n = \\dfrac{n}{2}[2a + (n-1)d] = \\dfrac{n}{2}(a + l)',
    plainText: 'S_n = n/2 × (first term + last term)',
    explanation: 'Sum of AP. If last term l is known, use S=n/2×(a+l). Useful for sum of all 2-digit multiples of k.',
    derivation: '',
    tags: ['AP', 'series', 'sum'],
    source: 'ppt',
  },
  {
    formulaId: 'APT-FOR-022',
    conceptSlug: 'number-system',
    title: 'If a+b+c=0 then a³+b³+c³=3abc',
    expression: 'a+b+c=0 \\Rightarrow a^3+b^3+c^3 = 3abc',
    plainText: 'When a+b+c=0, then a^3+b^3+c^3 = 3abc',
    explanation: 'Special case of a³+b³+c³-3abc=(a+b+c)(a²+b²+c²-ab-bc-ca). Useful when x+y+z=0.',
    derivation: 'Substitute a+b+c=0 into the full identity.',
    tags: ['algebra', 'identity', 'cubes'],
    source: 'rs_agarwal',
  },
  {
    formulaId: 'APT-FOR-023',
    conceptSlug: 'number-system',
    title: 'True Remainder (Successive Division)',
    expression: 'R = r_1 + r_2 \\cdot d_1 + r_3 \\cdot d_1 \\cdot d_2',
    plainText: 'True remainder = r1 + r2*d1 + r3*d1*d2',
    explanation: 'When a number is divided successively by d1, d2, d3 giving remainders r1, r2, r3, the true remainder when divided by d1×d2×d3.',
    derivation: 'Work backwards from the last quotient.',
    tags: ['remainder', 'successive-division', 'true-remainder'],
    source: 'ppt',
  },
]
