export const MODELS = [
  {
    modelId: 'APT-MOD-001',
    conceptSlug: 'number-system',
    name: 'Face Value & Place Value',
    description: 'Finding place value (local value) or face value of a digit in a numeral. Place value = digit × positional power of 10.',
    formulaIds: [],
    difficulty: 'easy',
  },
  {
    modelId: 'APT-MOD-002',
    conceptSlug: 'number-system',
    name: 'Types of Numbers',
    description: 'Identifying natural, whole, integer, even, odd, prime, composite, co-prime, twin-prime, and perfect numbers.',
    formulaIds: [],
    difficulty: 'easy',
  },
  {
    modelId: 'APT-MOD-003',
    conceptSlug: 'number-system',
    name: 'Divisibility Tests',
    description: 'Testing whether a number is divisible by 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 24, 25, 99 etc.',
    formulaIds: ['APT-FOR-019'],
    difficulty: 'easy',
  },
  {
    modelId: 'APT-MOD-004',
    conceptSlug: 'number-system',
    name: 'Unit Digit Calculation',
    description: 'Finding the unit digit of a^n or products of large numbers using cyclicity (repeating pattern of unit digits).',
    formulaIds: ['APT-FOR-018'],
    difficulty: 'medium',
  },
  {
    modelId: 'APT-MOD-005',
    conceptSlug: 'number-system',
    name: 'Trailing Zeros in Products & Factorials',
    description: 'Counting trailing zeros in n! or products like 5×10×15×...×50 using Legendre\'s formula for prime power in factorial.',
    formulaIds: ['APT-FOR-011', 'APT-FOR-012'],
    difficulty: 'medium',
  },
  {
    modelId: 'APT-MOD-006',
    conceptSlug: 'number-system',
    name: 'Division Algorithm & Remainders',
    description: 'Using Dividend = Divisor × Quotient + Remainder to find missing values. Finding number from divisor/quotient/remainder constraints.',
    formulaIds: ['APT-FOR-010'],
    difficulty: 'medium',
  },
  {
    modelId: 'APT-MOD-007',
    conceptSlug: 'number-system',
    name: 'Successive Division',
    description: 'A number divided successively by d1, d2, d3 leaving remainders r1, r2, r3. Find the number or remainder when divided by d1×d2×d3.',
    formulaIds: ['APT-FOR-010', 'APT-FOR-023'],
    difficulty: 'hard',
  },
  {
    modelId: 'APT-MOD-008',
    conceptSlug: 'number-system',
    name: 'Algebraic Identities for Simplification',
    description: 'Using (a+b)², (a-b)², a²-b², a³±b³ identities to simplify large numerical expressions.',
    formulaIds: ['APT-FOR-004', 'APT-FOR-005', 'APT-FOR-007', 'APT-FOR-008', 'APT-FOR-009'],
    difficulty: 'medium',
  },
  {
    modelId: 'APT-MOD-009',
    conceptSlug: 'number-system',
    name: 'Prime Number Testing',
    description: 'Checking if a number is prime by testing divisibility by all primes up to its square root.',
    formulaIds: [],
    difficulty: 'easy',
  },
  {
    modelId: 'APT-MOD-010',
    conceptSlug: 'number-system',
    name: 'Finding Missing Digits',
    description: 'Find unknown digit(s) in a number given divisibility conditions (divisible by 8 and 5, sum divisible by 9, etc.).',
    formulaIds: ['APT-FOR-019'],
    difficulty: 'medium',
  },
  {
    modelId: 'APT-MOD-011',
    conceptSlug: 'number-system',
    name: 'Sum of Series',
    description: 'Computing sums of natural numbers, even numbers, odd numbers, squares, cubes using standard formulas.',
    formulaIds: ['APT-FOR-001', 'APT-FOR-002', 'APT-FOR-003', 'APT-FOR-016', 'APT-FOR-017', 'APT-FOR-020', 'APT-FOR-021'],
    difficulty: 'medium',
  },
  {
    modelId: 'APT-MOD-012',
    conceptSlug: 'number-system',
    name: 'Remainder Theorems (xⁿ ± aⁿ)',
    description: 'Finding remainders using (xⁿ-aⁿ) divisibility by (x-a), (xⁿ+aⁿ) by (x+a), and (x+1)ⁿ divided by x.',
    formulaIds: ['APT-FOR-013', 'APT-FOR-014', 'APT-FOR-015'],
    difficulty: 'hard',
  },
  {
    modelId: 'APT-MOD-013',
    conceptSlug: 'number-system',
    name: 'Number of Factors & Prime Factorization',
    description: 'Finding total number of prime factors in expressions like (4)^11 × (7)^5 × (11)^2.',
    formulaIds: ['APT-FOR-012'],
    difficulty: 'medium',
  },
  {
    modelId: 'APT-MOD-014',
    conceptSlug: 'number-system',
    name: 'Largest/Smallest Numbers with Conditions',
    description: 'Finding smallest/largest n-digit number divisible by k, nearest number to N divisible by k, number to add/subtract for divisibility.',
    formulaIds: ['APT-FOR-010'],
    difficulty: 'easy',
  },
]
