// RS Agarwal Solved Examples (Ex.1 - Ex.52)
export const SOLVED_EXAMPLES = [
  {
    questionId: 'APT-Q-001',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-008',
    formulaIds: [],
    questionText: 'Simplify: 8888 + 888 + 88 + 8',
    questionType: 'mcq',
    options: ['A) 9862', 'B) 9872', 'C) 9782', 'D) 9726'],
    correctAnswer: 'B) 9872',
    difficulty: 'easy',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Add all terms column by column', formula: null, formulaExpression: '', calculation: '8888 + 888 + 88 + 8', result: '9872' },
      ],
      shortcut: 'Group: 8888+888 = 9776, 9776+88 = 9864, 9864+8 = 9872',
      commonMistake: 'Misaligning columns when adding numbers of different lengths.',
      timeToSolve: '20 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '7',
    sourceType: 'solved_example',
    tags: ['addition', 'simplification'],
  },
  {
    questionId: 'APT-Q-002',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-008',
    formulaIds: [],
    questionText: 'Simplify: 715632 - 631104 - 9874 - 999',
    questionType: 'mcq',
    options: ['A) 74555', 'B) 73555', 'C) 74455', 'D) 74565'],
    correctAnswer: 'A) 74555',
    difficulty: 'easy',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Add all numbers to subtract: 631104 + 9874 + 999', formula: null, formulaExpression: '', calculation: '631104 + 9874 + 999 = 641077', result: '641077' },
        { stepNumber: 2, explanation: 'Subtract from 715632', formula: null, formulaExpression: '', calculation: '715632 - 641077', result: '74555' },
      ],
      shortcut: 'Subtract all three numbers together rather than step by step.',
      commonMistake: 'Subtracting one by one introduces more arithmetic errors.',
      timeToSolve: '30 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '7',
    sourceType: 'solved_example',
    tags: ['subtraction', 'simplification'],
  },
  {
    questionId: 'APT-Q-003',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-010',
    formulaIds: [],
    questionText: 'What could be the maximum value of Q in the following equation? 5P9 + 3R7 + 2Q8 = 1114',
    questionType: 'mcq',
    options: ['A) 7', 'B) 8', 'C) 9', 'D) 6'],
    correctAnswer: 'C) 9',
    difficulty: 'easy',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Ones digit: 9+7+8=24, write 4 carry 2. Tens: 2+P+R+Q = carries 11 (with carry). So 2+P+R+Q = 11.', formula: null, formulaExpression: '', calculation: '2 + P + R + Q = 11', result: 'P + R + Q = 9' },
        { stepNumber: 2, explanation: 'To maximise Q, minimise P and R. Set P=0, R=0.', formula: null, formulaExpression: '', calculation: 'Q = 9 when P=0, R=0', result: 'Maximum Q = 9' },
      ],
      shortcut: 'From the tens column equation, Q is maximised when P=R=0.',
      commonMistake: 'Not accounting for carries from the ones column.',
      timeToSolve: '45 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '8',
    sourceType: 'solved_example',
    tags: ['missing-digit', 'addition'],
  },
  {
    questionId: 'APT-Q-004',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-008',
    formulaIds: ['APT-FOR-004'],
    questionText: 'Simplify: 1605 × 1605',
    questionType: 'mcq',
    options: ['A) 2576025', 'B) 2562025', 'C) 2576205', 'D) 2516025'],
    correctAnswer: 'A) 2576025',
    difficulty: 'easy',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Write as (1600+5)² using (a+b)²=a²+2ab+b²', formula: 'APT-FOR-004', formulaExpression: '(a+b)^2 = a^2 + 2ab + b^2', calculation: '(1600+5)² = 1600² + 2×1600×5 + 5²', result: '' },
        { stepNumber: 2, explanation: 'Calculate each term', formula: null, formulaExpression: '', calculation: '2,560,000 + 16,000 + 25', result: '2,576,025' },
      ],
      shortcut: 'Always split into (round number ± small number)² for fast squaring.',
      commonMistake: 'Forgetting the middle term 2ab.',
      timeToSolve: '30 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '8',
    sourceType: 'solved_example',
    tags: ['squares', 'algebraic-identity'],
  },
  {
    questionId: 'APT-Q-005',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-008',
    formulaIds: ['APT-FOR-005'],
    questionText: 'Simplify: 1398 × 1398',
    questionType: 'mcq',
    options: ['A) 1952604', 'B) 1954404', 'C) 1952404', 'D) 1954204'],
    correctAnswer: 'B) 1954404',
    difficulty: 'easy',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Write as (1400-2)² using (a-b)²=a²-2ab+b²', formula: 'APT-FOR-005', formulaExpression: '(a-b)^2 = a^2 - 2ab + b^2', calculation: '(1400-2)² = 1400² - 2×1400×2 + 2²', result: '' },
        { stepNumber: 2, explanation: 'Calculate', formula: null, formulaExpression: '', calculation: '1,960,000 - 5,600 + 4 = 1,954,404', result: '1,954,404' },
      ],
      shortcut: 'For numbers near 1400, use (1400-x)² form.',
      commonMistake: 'Using + instead of - for 2ab term.',
      timeToSolve: '30 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '8',
    sourceType: 'solved_example',
    tags: ['squares', 'algebraic-identity'],
  },
  {
    questionId: 'APT-Q-006',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-008',
    formulaIds: ['APT-FOR-007'],
    questionText: 'Evaluate: 796 × 796 - 204 × 204',
    questionType: 'mcq',
    options: ['A) 592000', 'B) 529000', 'C) 590200', 'D) 592200'],
    correctAnswer: 'A) 592000',
    difficulty: 'easy',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Apply a²-b² = (a+b)(a-b) with a=796, b=204', formula: 'APT-FOR-007', formulaExpression: 'a^2 - b^2 = (a+b)(a-b)', calculation: '(796+204)(796-204)', result: '' },
        { stepNumber: 2, explanation: 'Calculate', formula: null, formulaExpression: '', calculation: '1000 × 592 = 592,000', result: '592,000' },
      ],
      shortcut: 'Always check if numbers sum/differ to round numbers like 1000.',
      commonMistake: 'Computing each square separately — much slower.',
      timeToSolve: '15 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '8',
    sourceType: 'solved_example',
    tags: ['difference-of-squares', 'algebraic-identity'],
  },
  {
    questionId: 'APT-Q-007',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-008',
    formulaIds: ['APT-FOR-008'],
    questionText: 'Simplify: (789 × 789 × 789 + 211 × 211 × 211) ÷ (789 × 789 - 789 × 211 + 211 × 211)',
    questionType: 'mcq',
    options: ['A) 1000', 'B) 789', 'C) 578', 'D) 211'],
    correctAnswer: 'A) 1000',
    difficulty: 'medium',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Identify: numerator = a³+b³, denominator = a²-ab+b² with a=789, b=211', formula: 'APT-FOR-008', formulaExpression: 'a^3+b^3 = (a+b)(a^2-ab+b^2)', calculation: '(a³+b³)/(a²-ab+b²) = a+b', result: '' },
        { stepNumber: 2, explanation: 'Substitute', formula: null, formulaExpression: '', calculation: '789 + 211 = 1000', result: '1000' },
      ],
      shortcut: 'The fraction simplifies to (a+b) when numerator is a³+b³.',
      commonMistake: 'Trying to compute 789³ directly — unnecessary.',
      timeToSolve: '20 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '9',
    sourceType: 'solved_example',
    tags: ['sum-of-cubes', 'algebraic-identity'],
  },
  {
    questionId: 'APT-Q-008',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-008',
    formulaIds: ['APT-FOR-009'],
    questionText: 'Simplify: (658 × 658 × 658 - 328 × 328 × 328) ÷ (658 × 658 + 658 × 328 + 328 × 328)',
    questionType: 'mcq',
    options: ['A) 330', 'B) 986', 'C) 658', 'D) 328'],
    correctAnswer: 'A) 330',
    difficulty: 'medium',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Numerator = a³-b³, denominator = a²+ab+b² with a=658, b=328', formula: 'APT-FOR-009', formulaExpression: 'a^3-b^3 = (a-b)(a^2+ab+b^2)', calculation: '(a³-b³)/(a²+ab+b²) = a-b', result: '' },
        { stepNumber: 2, explanation: 'Substitute', formula: null, formulaExpression: '', calculation: '658 - 328 = 330', result: '330' },
      ],
      shortcut: 'Always look for a³-b³ / (a²+ab+b²) pattern = a-b.',
      commonMistake: 'Confusing a³+b³ and a³-b³ formulas.',
      timeToSolve: '20 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '9',
    sourceType: 'solved_example',
    tags: ['difference-of-cubes', 'algebraic-identity'],
  },
  {
    questionId: 'APT-Q-009',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-004',
    formulaIds: ['APT-FOR-018'],
    questionText: 'Find the unit\'s digit in the product (2467)^153 × (341)^72',
    questionType: 'mcq',
    options: ['A) 1', 'B) 3', 'C) 7', 'D) 9'],
    correctAnswer: 'C) 7',
    difficulty: 'medium',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Unit digit of (2467)^153: unit digit is 7. Cycle of 7: 7,9,3,1 (period 4). 153 mod 4 = 1, so unit digit = 7.', formula: 'APT-FOR-018', formulaExpression: '7^1=7, 7^2=49, 7^3=343, 7^4=2401 \\Rightarrow \\text{cycle: }7,9,3,1', calculation: '153 mod 4 = 1 → unit digit = 7', result: 'Unit digit of first term = 7' },
        { stepNumber: 2, explanation: 'Unit digit of (341)^72: unit digit is 1. 1 raised to any power = 1.', formula: null, formulaExpression: '', calculation: '1^72 = 1', result: 'Unit digit of second term = 1' },
        { stepNumber: 3, explanation: 'Unit digit of product = unit digit of 7×1', formula: null, formulaExpression: '', calculation: '7 × 1 = 7', result: 'Unit digit = 7' },
      ],
      shortcut: 'Find the cycle of the unit digit (1→1, 5→5, 6→6; 4,9→cycle 2; 2,3,7,8→cycle 4).',
      commonMistake: 'Using full exponent mod 4 when the base unit digit is 0,1,5,6 — those always give same digit.',
      timeToSolve: '45 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '11',
    sourceType: 'solved_example',
    tags: ['unit-digit', 'cyclicity', 'powers'],
  },
  {
    questionId: 'APT-Q-010',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-004',
    formulaIds: ['APT-FOR-018'],
    questionText: 'Find the unit\'s digit in (264)^102 + (264)^103',
    questionType: 'mcq',
    options: ['A) 0', 'B) 2', 'C) 4', 'D) 6'],
    correctAnswer: 'A) 0',
    difficulty: 'medium',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Unit digit of 264 is 4. Cycle of 4: 4,6,4,6 (period 2). 102 is even → unit digit = 6.', formula: null, formulaExpression: '', calculation: '4^102: 102 is even → unit digit = 6', result: 'Unit digit of (264)^102 = 6' },
        { stepNumber: 2, explanation: '103 is odd → unit digit of 4^103 = 4.', formula: null, formulaExpression: '', calculation: '4^103: 103 is odd → unit digit = 4', result: 'Unit digit of (264)^103 = 4' },
        { stepNumber: 3, explanation: 'Sum unit digits: 6+4=10, unit digit = 0', formula: null, formulaExpression: '', calculation: '6 + 4 = 10', result: 'Unit digit = 0' },
      ],
      shortcut: '4 has a 2-cycle: even power→6, odd power→4.',
      commonMistake: 'Forgetting to take unit digit of the sum (not just the individual terms).',
      timeToSolve: '30 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '11',
    sourceType: 'solved_example',
    tags: ['unit-digit', 'cyclicity'],
  },
  {
    questionId: 'APT-Q-011',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-013',
    formulaIds: ['APT-FOR-012'],
    questionText: 'Find the total number of prime factors in the expression (4)^11 × (7)^5 × (11)^2',
    questionType: 'mcq',
    options: ['A) 29', 'B) 27', 'C) 25', 'D) 18'],
    correctAnswer: 'A) 29',
    difficulty: 'medium',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Express 4 as prime: 4 = 2², so 4^11 = 2^22', formula: null, formulaExpression: '', calculation: '4^{11} = (2^2)^{11} = 2^{22}', result: '22 factors of 2' },
        { stepNumber: 2, explanation: '7^5 contributes 5 prime factors of 7', formula: null, formulaExpression: '', calculation: '7^5 \\rightarrow 5 \\text{ factors}', result: '5 factors of 7' },
        { stepNumber: 3, explanation: '11^2 contributes 2 prime factors of 11', formula: null, formulaExpression: '', calculation: '11^2 \\rightarrow 2 \\text{ factors}', result: '2 factors of 11' },
        { stepNumber: 4, explanation: 'Total prime factors = sum of all exponents', formula: null, formulaExpression: '', calculation: '22 + 5 + 2 = 29', result: 'Total = 29' },
      ],
      shortcut: 'Prime factors count = sum of all exponents after prime factorization.',
      commonMistake: 'Counting number of distinct primes (3) instead of total prime factors (29).',
      timeToSolve: '30 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '11',
    sourceType: 'solved_example',
    tags: ['prime-factors', 'exponents'],
  },
  {
    questionId: 'APT-Q-012',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-005',
    formulaIds: ['APT-FOR-011'],
    questionText: 'What is the number of zeros at the end of the product of the numbers from 1 to 100?',
    questionType: 'mcq',
    options: ['A) 22', 'B) 24', 'C) 25', 'D) 28'],
    correctAnswer: 'B) 24',
    difficulty: 'medium',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Trailing zeros = number of times 10 divides 100!. Since 10=2×5, and factors of 2 >> factors of 5, count factors of 5 in 100!', formula: 'APT-FOR-011', formulaExpression: '\\left\\lfloor\\frac{100}{5}\\right\\rfloor + \\left\\lfloor\\frac{100}{25}\\right\\rfloor + \\left\\lfloor\\frac{100}{125}\\right\\rfloor + \\cdots', calculation: '', result: '' },
        { stepNumber: 2, explanation: 'Calculate each term', formula: null, formulaExpression: '', calculation: '\\lfloor 100/5 \\rfloor = 20,\\quad \\lfloor 100/25 \\rfloor = 4,\\quad \\lfloor 100/125 \\rfloor = 0', result: '' },
        { stepNumber: 3, explanation: 'Sum all terms', formula: null, formulaExpression: '', calculation: '20 + 4 = 24', result: '24 trailing zeros' },
      ],
      shortcut: 'Just keep dividing by 5 and summing quotients until quotient becomes 0.',
      commonMistake: 'Forgetting multiples of 25 (which contribute two 5s each).',
      timeToSolve: '30 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '12',
    sourceType: 'solved_example',
    tags: ['trailing-zeros', 'factorial'],
  },
  {
    questionId: 'APT-Q-013',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-006',
    formulaIds: ['APT-FOR-010'],
    questionText: 'On dividing 15968 by a certain number, the quotient is 89 and the remainder is 37. Find the divisor.',
    questionType: 'mcq',
    options: ['A) 168', 'B) 179', 'C) 189', 'D) 175'],
    correctAnswer: 'B) 179',
    difficulty: 'easy',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Use: Divisor = (Dividend - Remainder) / Quotient', formula: 'APT-FOR-010', formulaExpression: '\\text{Divisor} = \\frac{\\text{Dividend} - \\text{Remainder}}{\\text{Quotient}}', calculation: '(15968 - 37) / 89', result: '' },
        { stepNumber: 2, explanation: 'Calculate', formula: null, formulaExpression: '', calculation: '15931 / 89 = 179', result: 'Divisor = 179' },
      ],
      shortcut: 'Rearrange division algorithm: Divisor = (Dividend - Remainder) ÷ Quotient.',
      commonMistake: 'Adding remainder instead of subtracting.',
      timeToSolve: '20 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '12',
    sourceType: 'solved_example',
    tags: ['division-algorithm', 'divisor'],
  },
  {
    questionId: 'APT-Q-014',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-006',
    formulaIds: ['APT-FOR-010'],
    questionText: 'A number when divided by 114, leaves remainder 21. If the same number is divided by 19, find the remainder.',
    questionType: 'mcq',
    options: ['A) 1', 'B) 2', 'C) 3', 'D) 7'],
    correctAnswer: 'B) 2',
    difficulty: 'medium',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Let number = 114k + 21. Express 21 in terms of 19: 21 = 19×1 + 2', formula: 'APT-FOR-010', formulaExpression: '114k + 21 = 19 \\times 6k + 19 \\times 1 + 2 = 19(6k+1) + 2', calculation: '114 = 19×6, so 114k = 19×6k', result: '' },
        { stepNumber: 2, explanation: 'Number = 19(6k+1) + 2, so remainder when divided by 19 is 2', formula: null, formulaExpression: '', calculation: 'Remainder = 2', result: 'Remainder = 2' },
      ],
      shortcut: 'If divisor₂ divides divisor₁, remainder₂ = remainder₁ mod divisor₂.',
      commonMistake: 'Thinking remainder stays 21 when dividing by 19.',
      timeToSolve: '30 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '12',
    sourceType: 'solved_example',
    tags: ['remainder', 'divisibility'],
  },
  {
    questionId: 'APT-Q-015',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-007',
    formulaIds: ['APT-FOR-010', 'APT-FOR-023'],
    questionText: 'A number being successively divided by 3, 5 and 8 leaves remainders 1, 4 and 7 respectively. Find the respective remainders if the order of divisors be reversed (8, 5, 3).',
    questionType: 'mcq',
    options: ['A) 6, 4, 2', 'B) 5, 3, 2', 'C) 4, 3, 1', 'D) 3, 2, 1'],
    correctAnswer: 'A) 6, 4, 2',
    difficulty: 'hard',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Work backwards to find the number. If div by 8 gives q=1, r=7: z=8×1+7=15. If div by 5 gives z=15, r=4: y=5×15+4=79. If div by 3 gives y=79, r=1: x=3×79+1=238.', formula: null, formulaExpression: '', calculation: 'Number x = 238', result: 'x = 238' },
        { stepNumber: 2, explanation: 'Now divide 238 by 8, 5, 3 in order', formula: null, formulaExpression: '', calculation: '238 ÷ 8 = 29 r 6; 29 ÷ 5 = 5 r 4; 5 ÷ 3 = 1 r 2', result: 'Remainders: 6, 4, 2' },
      ],
      shortcut: 'First find the actual number by working backwards, then apply new division order.',
      commonMistake: 'Not finding the actual number first.',
      timeToSolve: '90 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '12',
    sourceType: 'solved_example',
    tags: ['successive-division', 'remainders'],
  },
  {
    questionId: 'APT-Q-016',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-006',
    formulaIds: ['APT-FOR-010'],
    questionText: 'In a division sum, the divisor is ten times the quotient and five times the remainder. If the remainder is 46, determine the dividend.',
    questionType: 'mcq',
    options: ['A) 5336', 'B) 5330', 'C) 5230', 'D) 5430'],
    correctAnswer: 'A) 5336',
    difficulty: 'medium',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Remainder = 46. Divisor = 5 × 46 = 230. Quotient = Divisor/10 = 23.', formula: null, formulaExpression: '', calculation: 'Divisor=230, Quotient=23', result: '' },
        { stepNumber: 2, explanation: 'Dividend = Divisor × Quotient + Remainder', formula: 'APT-FOR-010', formulaExpression: '\\text{Dividend} = \\text{Divisor} \\times \\text{Quotient} + \\text{Remainder}', calculation: '230 × 23 + 46 = 5290 + 46 = 5336', result: '5336' },
      ],
      shortcut: 'Find all three components from remainder, then apply division algorithm.',
      commonMistake: 'Confusing divisor with quotient.',
      timeToSolve: '45 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '13',
    sourceType: 'solved_example',
    tags: ['division-algorithm', 'word-problem'],
  },
  {
    questionId: 'APT-Q-017',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-012',
    formulaIds: ['APT-FOR-013'],
    questionText: 'Find the remainder when 9^6 + 7 is divided by 8.',
    questionType: 'mcq',
    options: ['A) 0', 'B) 1', 'C) 2', 'D) 3'],
    correctAnswer: 'A) 0',
    difficulty: 'medium',
    solution: {
      steps: [
        { stepNumber: 1, explanation: '(9⁶-1⁶) is divisible by (9-1)=8 since xⁿ-aⁿ is divisible by x-a for all n', formula: 'APT-FOR-013', formulaExpression: '(x^n - a^n) \\text{ divisible by } (x-a)', calculation: '(9^6 - 1) \\text{ is divisible by } 8', result: '' },
        { stepNumber: 2, explanation: 'So 9⁶-1+8 = 9⁶+7 is also divisible by 8', formula: null, formulaExpression: '', calculation: '(9^6+7) = (9^6-1) + 8', result: 'Remainder = 0' },
      ],
      shortcut: 'Rewrite expression as multiple of divisor.',
      commonMistake: 'Trying to compute 9⁶ directly.',
      timeToSolve: '30 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '13',
    sourceType: 'solved_example',
    tags: ['remainder', 'algebraic-divisibility'],
  },
  {
    questionId: 'APT-Q-018',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-012',
    formulaIds: ['APT-FOR-015'],
    questionText: 'Find the remainder when (397)^3589 + 5 is divided by 398.',
    questionType: 'mcq',
    options: ['A) 2', 'B) 4', 'C) 6', 'D) 8'],
    correctAnswer: 'B) 4',
    difficulty: 'hard',
    solution: {
      steps: [
        { stepNumber: 1, explanation: '(xⁿ+aⁿ) is divisible by (x+a) when n is odd. Here x=397, a=1, n=3589 (odd), x+a=398.', formula: 'APT-FOR-015', formulaExpression: '(x^n + a^n) \\text{ divisible by } (x+a) \\text{ for odd } n', calculation: '(397^{3589}+1^{3589}) \\text{ divisible by } 398', result: '' },
        { stepNumber: 2, explanation: 'So (397³⁵⁸⁹+1) is divisible by 398. We need (397³⁵⁸⁹+5).', formula: null, formulaExpression: '', calculation: '(397^{3589}+5) = (397^{3589}+1) + 4', result: '' },
        { stepNumber: 3, explanation: 'Since (397³⁵⁸⁹+1) is divisible by 398, remainder of (397³⁵⁸⁹+5) ÷ 398 = 4', formula: null, formulaExpression: '', calculation: 'Remainder = 4', result: '4' },
      ],
      shortcut: 'Adjust the constant: (xⁿ+aⁿ+k) divided by (x+a) gives remainder k (if k < divisor).',
      commonMistake: 'Not recognizing the odd-power formula pattern.',
      timeToSolve: '60 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '13',
    sourceType: 'solved_example',
    tags: ['remainder', 'xn+an', 'algebraic-divisibility'],
  },
  {
    questionId: 'APT-Q-019',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-012',
    formulaIds: ['APT-FOR-013'],
    questionText: 'Find the remainder when 7^126 is divided by 48.',
    questionType: 'mcq',
    options: ['A) 0', 'B) 1', 'C) 7', 'D) 47'],
    correctAnswer: 'B) 1',
    difficulty: 'hard',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Write 7^126 = (7²)^63 = 49^63', formula: null, formulaExpression: '7^{126} = (7^2)^{63} = 49^{63}', calculation: '', result: '' },
        { stepNumber: 2, explanation: '(49^63 - 1^63) is divisible by (49-1)=48 since xⁿ-aⁿ divisible by x-a', formula: 'APT-FOR-013', formulaExpression: '(49^{63}-1) \\text{ divisible by } 48', calculation: '', result: '' },
        { stepNumber: 3, explanation: 'So 49^63 ≡ 1 (mod 48), meaning remainder = 1', formula: null, formulaExpression: '', calculation: 'Remainder of 7^{126} ÷ 48 = 1', result: '1' },
      ],
      shortcut: 'Rewrite as perfect power, then apply (xⁿ-1) divisibility.',
      commonMistake: 'Not converting to a form where the formula applies cleanly.',
      timeToSolve: '45 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '13',
    sourceType: 'solved_example',
    tags: ['remainder', 'xn-an', 'powers'],
  },
  {
    questionId: 'APT-Q-020',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-011',
    formulaIds: ['APT-FOR-001'],
    questionText: 'Given that 1² + 2² + 3² + ... + 10² = 385, find the value of 2² + 4² + 6² + ... + 20².',
    questionType: 'mcq',
    options: ['A) 770', 'B) 1155', 'C) 1540', 'D) 3850'],
    correctAnswer: 'C) 1540',
    difficulty: 'medium',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Factor out 2² from each term: 2²+4²+...+20² = 2²(1²+2²+...+10²)', formula: null, formulaExpression: '(2k)^2 = 4k^2', calculation: '4(1^2+2^2+\\cdots+10^2)', result: '' },
        { stepNumber: 2, explanation: 'Substitute given sum', formula: null, formulaExpression: '', calculation: '4 \\times 385 = 1540', result: '1540' },
      ],
      shortcut: 'Factor out 4 from the even-squares series.',
      commonMistake: 'Thinking the sum just doubles.',
      timeToSolve: '20 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '9',
    sourceType: 'solved_example',
    tags: ['sum-of-squares', 'series'],
  },
  {
    questionId: 'APT-Q-021',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-014',
    formulaIds: ['APT-FOR-010'],
    questionText: 'Find the smallest number to be added to 1000 so that 45 divides the sum exactly.',
    questionType: 'mcq',
    options: ['A) 10', 'B) 25', 'C) 35', 'D) 45'],
    correctAnswer: 'C) 35',
    difficulty: 'easy',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Divide 1000 by 45 and find remainder', formula: null, formulaExpression: '', calculation: '1000 = 45 \\times 22 + 10', result: 'Remainder = 10' },
        { stepNumber: 2, explanation: 'Number to add = Divisor - Remainder = 45-10', formula: null, formulaExpression: '', calculation: '45 - 10 = 35', result: '35' },
      ],
      shortcut: 'Number to add = divisor - remainder (if remainder ≠ 0).',
      commonMistake: 'Adding the remainder instead of (divisor - remainder).',
      timeToSolve: '20 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '11',
    sourceType: 'solved_example',
    tags: ['divisibility', 'number-to-add'],
  },
  {
    questionId: 'APT-Q-022',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-014',
    formulaIds: ['APT-FOR-010'],
    questionText: 'Find the smallest number of five digits which is exactly divisible by 476.',
    questionType: 'mcq',
    options: ['A) 10472', 'B) 10000', 'C) 10476', 'D) 10252'],
    correctAnswer: 'A) 10472',
    difficulty: 'easy',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Smallest 5-digit number = 10000. Divide 10000 by 476.', formula: null, formulaExpression: '', calculation: '10000 = 476 \\times 21 + 4', result: 'Remainder = 4' },
        { stepNumber: 2, explanation: 'Add (476-4)=472 to 10000 to get next multiple of 476', formula: null, formulaExpression: '', calculation: '10000 + 472 = 10472', result: '10472' },
      ],
      shortcut: 'Answer = 10000 + (476 - remainder).',
      commonMistake: 'Just adding 476 to 10000 without checking divisibility.',
      timeToSolve: '30 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '11',
    sourceType: 'solved_example',
    tags: ['smallest-number', 'divisibility'],
  },
  {
    questionId: 'APT-Q-023',
    conceptSlug: 'number-system',
    modelId: 'APT-MOD-014',
    formulaIds: ['APT-FOR-010'],
    questionText: 'Find the greatest number of five digits which is exactly divisible by 47.',
    questionType: 'mcq',
    options: ['A) 99969', 'B) 99976', 'C) 99947', 'D) 99999'],
    correctAnswer: 'A) 99969',
    difficulty: 'easy',
    solution: {
      steps: [
        { stepNumber: 1, explanation: 'Greatest 5-digit number = 99999. Divide by 47.', formula: null, formulaExpression: '', calculation: '99999 = 47 \\times 2127 + 30', result: 'Remainder = 30' },
        { stepNumber: 2, explanation: 'Subtract remainder to get greatest divisible number', formula: null, formulaExpression: '', calculation: '99999 - 30 = 99969', result: '99969' },
      ],
      shortcut: 'Greatest number divisible = (largest n-digit number) - remainder.',
      commonMistake: 'Adding the remainder instead of subtracting.',
      timeToSolve: '25 seconds',
    },
    source: 'rs_agarwal',
    sourcePage: '11',
    sourceType: 'solved_example',
    tags: ['greatest-number', 'divisibility'],
  },
]
